### ISSUE TITLE
Dashboard is empty

### ISSUE THREAD

**Issue by chucky2305** [moshe/elasticsearch-comrade#799]
the relevant section in my docker-compose.yml

```
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
        ports:
            - "9209:9200"
        environment:
            - "discovery.type=single-node"
            - "bootstrap.memory_lock=true"
            - "ES_JAVA_OPTS=-Xms108m -Xmx108m"
            - "xpack.security.enabled=false"
            - "http.cors.enabled=true"
            - "http.cors.allow-origin=*"

    elasticsearch-dashboard:
        container_name: elasticsearch_dashboard
        depends_on:
            - elasticsearch
        image: mosheza/elasticsearch-comrade:v1.2.0
        environment:
            - "COMRADE_HOST:elasticsearch"
            - "COMRADE_PORT:9200"
            - "COMRADE_DEBUG:1"
        ports:
            - "8001:8000"
```

But when i open the comrade dashboard on http://localhost:8001 in get a dark but empty page.

Here are the log lines that comrade produces:

```
elasticsearch_dashboard    | /app/comrade/static/index.html
elasticsearch_dashboard    | [2021-12-14 09:19:15 +0000] - (sanic.access)[INFO][172.30.8.1:51464]: GET http://localhost:8001/  200 2472
elasticsearch_dashboard    | [2021-12-14 09:19:16 +0000] - (sanic.access)[INFO][172.30.8.1:51464]: GET http://localhost:8001/api/v1/clients  200 2
elasticsearch_dashboard    | /app/comrade/static/index.html
elasticsearch_dashboard    | [2021-12-14 09:19:31 +0000] - (sanic.access)[INFO][172.30.8.1:51462]: GET http://localhost:8001/  200 2472
elasticsearch_dashboard    | [2021-12-14 09:19:32 +0000] - (sanic.access)[INFO][172.30.8.1:51462]: GET http://localhost:8001/api/v1/clients  200 2
elasticsearch_dashboard    | /app/comrade/static/index.html
elasticsearch_dashboard    | [2021-12-14 09:19:47 +0000] - (sanic.access)[INFO][172.30.8.1:51492]: GET http://localhost:8001/  200 2472
elasticsearch_dashboard    | [2021-12-14 09:19:48 +0000] - (sanic.access)[INFO][172.30.8.1:51492]: GET http://localhost:8001/api/v1/clients  200 2
elasticsearch_dashboard    | /app/comrade/static/index.html
elasticsearch_dashboard    | [2021-12-14 09:19:49 +0000] - (sanic.access)[INFO][172.30.8.1:51492]: GET http://localhost:8001/  200 2472
elasticsearch_dashboard    | [2021-12-14 09:19:50 +0000] - (sanic.access)[INFO][172.30.8.1:51492]: GET http://localhost:8001/api/v1/clients  200 2
elasticsearch_dashboard    | [2021-12-14 09:20:47 +0000] [6] [ERROR] Transport closed @ ('172.30.8.1', 51522) and exception experienced during error handling
elasticsearch_dashboard    | /app/comrade/static/index.html
elasticsearch_dashboard    | [2021-12-14 09:26:55 +0000] - (sanic.access)[INFO][172.30.8.1:51600]: GET http://localhost:8001/  200 2472
elasticsearch_dashboard    | [2021-12-14 09:26:55 +0000] - (sanic.access)[INFO][172.30.8.1:51600]: GET http://localhost:8001/api/v1/clients  200 2
elasticsearch_dashboard    | /app/comrade/static/index.html
elasticsearch_dashboard    | [2021-12-14 09:26:56 +0000] - (sanic.access)[INFO][172.30.8.1:51600]: GET http://localhost:8001/  200 2472
elasticsearch_dashboard    | [2021-12-14 09:26:57 +0000] - (sanic.access)[INFO][172.30.8.1:51600]: GET http://localhost:8001/api/v1/clients  200 2
elasticsearch_dashboard    | [2021-12-14 09:27:55 +0000] [6] [ERROR] Transport closed @ ('172.30.8.1', 51602) and exception experienced during error handling

```

Can someone help me with this?
